spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate crée/met à jour les tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Exécuter data.sql APRÈS la création des tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.servlet.context-path=/api
server.port=8090

jwt.secret.key=${JWT_SECRET_KEY}

spring.mail.host=${MAIL_HOST}
spring.mail.port=465
spring.mail.username=${mail.from}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.connection-timeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.write-timeout=50000
spring.mail.default-encoding=UTF-8
mail.from=${MAIL_USERNAME}